const list = [
  {
    id: 1,
    img: "https://rukminim1.flixcart.com/image/832/832/k0zlsi80/jacket/4/h/w/xxl-mens-jkt-009-black-candy-house-original-imafg4hz7xz6pjpr.jpeg?q=70&quot&quot",
    brand: "Christy World",
    description: "Full Sleeve Solid Men Padded Jacket",
    discountPrice: 649,
    price: 1000,
    qty: 1,
  },
  {
    id: 2,
    img: "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/r/h/r/42-lj7160-lzard-original-imaggqhzx2bffpr8.jpeg?q=70",
    brand: "Lzard ",
    description: "Regular Men Light Blue Jeans",
    price: 849,
    qty: 1,
  },
  {
    id: 3,
    img: "https://rukminim1.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-ausk0165-ausk-original-imaghu9fbhcgf2za.jpeg?q=70",
    brand: "AUSK ",
    description: "Striped Men Round Neck Blue, Black T-Shirt",
    price: 1500,
    qty: 1,
  },
  {
    id: 4,
    img: "https://rukminim1.flixcart.com/image/312/312/keaaavk0/computer/x/m/y/lenovo-na-laptop-original-imafuzt8r5jqppfn.jpeg?q=70",
    brand: "Lenovo IdeaPad 3 Celeron Dual Core",
    description: "(8 GB/256 GB SSD/Windows 11 Home,15.5Inch, Platinum Gray,1.7Kg, With MS Office",
    price: 29990, 
    qty: 1,
  },
  {
    id: 5,
    img: "https://rukminim1.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/k/y/d/iphone-11-256-u-mwm82hn-a-apple-0-original-imafkg25mhaztxns.jpeg?q=70",
    brand: "Apple iphone 11",
    description: "White (128GB)",
    price: 48999, 
    qty: 1,
  },
  
  {
    id: 6,
    img: "https://rukminim1.flixcart.com/image/612/612/l2krs7k0/cycle/r/u/h/rustler-with-integrated-carrier-85-assembled-26-16-5-hrx-54-original-imagdw3fah6zhwxy.jpeg?q=70",
    brand: "HRX Rustler",
    description: "Single Speed,Multicolor",
    price: 15000 ,
    qty: 1,
  },
{
  id: 7,
  img: "https://rukminim1.flixcart.com/image/612/612/xif0q/jean/b/x/a/26-1-button-highrise-blue-tyffyn-original-imafwyffmw6n8fg9-bb.jpeg?q=70",
  brand: "TYFFYN ",
  description: "Slim Women Blue Jeans",
  price:  499,
  qty: 1,
},
{
  id: 8,
  img: "https://rukminim1.flixcart.com/image/495/594/xif0q/top/d/a/u/s-dmp338-dmp-fashion-original-imagefhzedmqjmx9-bb.jpeg?q=50",
  brand: "DMP FASHION",
  description: "Brown, Full Sleeves",
  price: 329 ,
  qty: 1,
},
{
  id: 9,
  img: "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/u/w/r/m-greenhar-kurti-dup-aarti-fahsion-original-imag7h3x3vbhzpge-bb.jpeg?q=70",
  brand: "stylistico",
  description: "Women Kurta and Dupatta Set Viscose Rayon",
  price: 1599 ,
  qty: 1,
},
{
  id: 10,
  img: "https://rukminim1.flixcart.com/image/612/612/keq058w0-0/slipper-flip-flop/u/m/n/9-combo-208-black-209-white-monoction-white-original-imafvc7dfmk9kaye.jpeg?q=70",
  brand: "Monoction ",
  description: "Combo Pack of 2 Pair New White fashion Reguler stylish Flip Flop Slides Slipper for Men(Slides Flip flops) Slides  (White 9) ",
  price: 499 ,
  qty: 1,
},
{
  id: 11,
  img: "https://rukminim1.flixcart.com/image/612/612/xif0q/sandal/n/m/8/-original-imagggggrukft8kz.jpeg?q=70",
  brand: "Denill ",
  description: "Women Green Flats Sandal",
  price: 499 ,
  qty: 1,
},
{
  id: 12,
  img: "https://rukminim1.flixcart.com/image/495/594/kzygpzk0/shoe/v/c/z/7-386917-7-puma-peony-white-lotus-original-imagbuf7ygdykfrr.jpeg?q=50",
  brand: "PUMA",
  description: "Fiona Wn's Slipon Sneakers For Women(Pink)",
  price: 1599 ,
  qty: 1,
},
{
  id: 13,
  img: "https://rukminim1.flixcart.com/image/200/200/hair-dryer/c/t/g/philips-hp8100-46-original-imaemymzuxrnzfjb.jpeg?q=70",
  brand: "PHILIPSE",
  description: "Best Of Hair Dryer",
  price: 1199 ,
  qty: 1,
},
{
  id: 14,
  img: "https://rukminim1.flixcart.com/image/200/200/ji0lbbk0/recliner/q/n/7/maroon-pu-leatherette-emporiummaroon-westido-original-imaf5wr5x27c6gaq.jpeg?q=70",
  brand: "Recliner",
  description: "Cozy Corners",
  price: 15999 ,
  qty: 1,
},
{
  id: 15,
  img: "https://rukminim1.flixcart.com/image/612/612/khwbde80/mascara/t/j/t/9-2-hypercurl-mascara-washable-maybelline-new-york-original-imafxt6ucwyfgvaf.jpeg?q=70",
  brand: "MAYBELLINE NEW YORK",
  description: "Hypercurl Mascara Washable 9.2 ml  (Black)",
  price: 295 ,
  qty: 1,
},
{
  id: 16,
  img: "https://rukminim1.flixcart.com/image/200/200/xif0q/cup-saucer/m/z/o/ssc001-a-to-z-original-imagjqby7tf8tezt.jpeg?q=70",
  brand: "A to Z Pack of 6 Stainless Steel SS CUP",
  description: "Steel, Cup Set",
  price: 264 ,
  qty: 1,
},
{
  id: 17,
  img: "https://rukminim1.flixcart.com/image/612/612/kkoc70w0/ukulele/y/v/g/jrz21uk-21-with-bag-and-picks-natural-juarez-original-imafzytynzef7ymh.jpeg?q=70",
  brand: "Juarez JRZ21UK/NA Soprano Ukulele",
  description: "Overall Length - 59.5 cm",
  price:  2299,
  qty: 1,
},
{
  id: 18,
  img: "https://rukminim1.flixcart.com/image/312/312/kg15ocw0/refrigerator-new/p/t/m/592hsmtb-na-motorola-original-imafwcn8yynzypvv.jpeg?q=70",
  brand: "Motorola 592 L Smart Wifi Enabled Frost Free Side by Side Refrigerator",
  description: "Premium Black,592HSMTB",
  price: 56799 ,
  qty: 1,
},
{
  id: 19,
  img: "https://rukminim1.flixcart.com/image/612/612/kpr8k280/headphone/v/n/9/bbd-l-21-wireless-bluetooth-headphone-waterproof-ipx5-blue-seed-original-imag3x8yv7fg9af9.jpeg?q=70",
  brand: "FD1 S_S L21 Wireless bluetooth headphone ",
  description: "Waterproof Stereo Headset Bluetooth Headset (Black,True Wireless)",
  price: 295 ,
  qty: 1,
},
{
  id: 20,
  img: "https://rukminim1.flixcart.com/image/612/612/xif0q/combo-kit/o/l/x/red-onion-black-seed-oil-ultimate-hair-care-kit-shampoo-hair-original-imaggkszhs4uev9j.jpeg?q=70",
  brand: "Phillauri Red Onion Black Seed Oil",
  description: "Ultimate Hair Care Kit (Shampoo + Hair Conditioner + Hair Oil,3Items in the set)",
  price: 299 ,
  qty: 1,
},
{
  id: 21,
  img: "https://rukminim1.flixcart.com/image/612/612/kgfg2vk0/backpack/u/m/t/jersey-45-l-laptop-backpack-p-037-backpack-provogue-45-original-imafwnh5vu75hh3z.jpeg?q=70",
  brand: "PROVOGUE ",
  description: "Large 45 L Laptop Backpack JERSEY 45 L Laptop Backpack  (Green)",
  price: 818 ,
  qty: 1,
},




];

export default list;